name: Publish Package

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Install
        run: npm install

      - name: Generate Icon Components
        run: npm run generate-icons

      - name: Build Package
        run: |
          npm run build:vite
          npm run build:tsc
          npm run build:copy

      - name: Prepare Tag
        id: tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "TAG_NAME=dist-$TAG_NAME" >> $GITHUB_OUTPUT
        env:
          TAG_NAME: ${{ github.ref_name }}

      - name: Publish Package
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          tag_message: "Release ${{ github.ref_name }}"
